name: index-rebalancing-research
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab=4.2
  - matplotlib=3.7.1
  - numpy=1.23.5
  - pandas=1.5.3
  - pip=24.0
  - scikit-learn=1.2.2
  - pip:
      - datefinder==0.7.3
      - keras==2.12.0
      - pdfplumber==0.10.4
      - pypdf2==3.0.1
      - tabula-py==2.9.0
      - tensorflow==2.12.0
